<!--About City Time-->
<article>
    <h2>Developed for fun just for you!</h2>
    Have fun converting times all across the globe, know if your meeting is schedule for the afternoon or morning.
</article>

<div class="datetime-container">
    <div class="datetime">
        <div class="timed"></div>
    </div>
</div>
<div class="qoute-container">
    <blockquote id="qoute">
    There is no qoute...
    </blockquote>
</div>

<article>
    <h4>Get in touch?</h4>
    <div class="feature-discovery">
        <div class="tap-target" id="contactTapTarget" data-target="openTapTarget">
            <div class="tap-target-content">
                <h5>Contact Us!</h5>
                <p>Feel free to reach out to us through the following contact details:</p>
                <p><strong>Email:</strong> techyaluna314@gmail.com</p>
                <p><strong>Phone:</strong> +260 770 215 265</p>
                <p><strong>Address:</strong> Riverside, Kitwe, Zambia</p>
            </div>
        </div>
        <a class="btn" id="openTapTarget"><i class="material-icons">view_list</i></a>
    </div>
</article>
